### ISSUE TITLE
Improperly Handles hyphenated drug names (Fluorofentanyl vs Para-Fluorofentanyl

### ISSUE THREAD

**Issue by Knoxort** [UK-IPOP/drug-extraction#82]
We found that the term "Fluorofentanyl" had been overcounted in our results. Upon investigation, we found that the hyphen "para-fluorofentanyl" was imporperly handled, so that "fluorofentanyl" was matched with a simlalarity score of one. I've attached a screenshot of the output joined with the searched file as well as a CSV showing the whole file.
[Example of Hyphenation Error, Fluororfent vs P-Fluorofent.csv](https://github.com/UK-IPOP/drug-extraction/files/15079238/Example.of.Hyphenation.Error.Fluororfent.vs.P-Fluorofent.csv)

![image](https://github.com/UK-IPOP/drug-extraction/assets/4002257/dee8f7b6-3c40-46e0-b468-11682cf20224)

**Comment by nanthony007** [comment]
@trokon resolved w/ #83 

New release followed. 

Should be available (v1.3.0 in PyPI)
