### ISSUE TITLE
_meta 

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/drug-extraction#85]
Can you confirm what is meant by the _meta version of drug_meta?

**Comment by nanthony007** [comment]
I believe you found this in the [UK-IPOP/open-data-pipeline](https://github.com/UK-IPOP/open-data-pipeline) repository. The [documentation](https://github.com/UK-IPOP/open-data-pipeline?tab=readme-ov-file#drug-columns) suggests that column is the "*" (anything) category column. It would be adapting the `metadata` column from this tool to wide form thus being drug categories (drug_meta = drug related, fentanyl_meta would contain all fentanyl related cases).
